name: Docker
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Code format check
              run: npx prettier --check "src/**/*.{ts,tsx}"

            - name: Install Dependencies
              run: yarn

            - name: Linting
              run: yarn lint

            - name: Run Tests
              run: yarn test:ci
