name: Docker Packaging [Rollups]
on:
    pull_request:
        paths:
            - 'apps/rollups/**'
            - 'packages/**'
    push:
        tags:
            - v*
env:
    image_name: rollups-explorer

concurrency:
    group: ${{github.workflow}}-${{github.ref_name}}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'yarn'

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Code format check
              run: yarn format:check

            - name: Linting
              run: yarn lint

            - name: Run Tests
              run: yarn test:ci

            - name: Set Up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set Up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2

            - name: Docker Meta
              id: docker_meta
              uses: docker/metadata-action@v4
              with:
                  images: |
                      name=ghcr.io/${{ github.repository_owner }}/${{ env.image_name }}
                      name=docker.io/${{ github.repository_owner }}/${{ env.image_name }},enable=${{ github.repository_owner == 'cartesi' }}
                  tags: |
                      type=semver,pattern={{version}}
                      type=ref,event=branch
                      type=ref,event=pr
                      type=sha,format=long

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              if: ${{ github.repository_owner == 'cartesi' && github.ref_type == 'tag'}}
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build & Push Docker Image
              id: docker_build
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: docker/Dockerfile-rollups
                  tags: ${{ steps.docker_meta.outputs.tags }}
                  labels: ${{ steps.docker_meta.outputs.labels }}
                  builder: ${{ steps.buildx.outputs.name }}
                  push: true
